# Generated by Django 5.2.3 on 2025-07-02 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agent',
            options={'ordering': ('-last_seen',)},
        ),
    ]
