# Generated by Django 5.2.3 on 2025-07-02 03:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_agent_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
