# Generated by Django 5.2.3 on 2025-07-02 03:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_agent_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='hardware_uuid',
            field=models.CharField(default='', unique=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
