# Generated by Django 5.2.3 on 2025-07-02 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_agent_hardware_uuid_alter_agent_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='type',
            field=models.CharField(choices=[('UPGRADE_ALL_APPS', 'Upgrade apps'), ('UPDATE_OS', 'Update OS'), ('STOP_AGENT', 'Stop agent')], max_length=30),
        ),
    ]
