# Generated by Django 5.2.3 on 2025-07-02 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_command_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='type',
            field=models.CharField(choices=[('UPGRADE_ALL_APPS', 'Upgrade all apps'), ('UPGRADE_APP', 'Upgrade app'), ('UPDATE_OS', 'Update OS'), ('STOP_AGENT', 'Stop agent')], max_length=30),
        ),
    ]
