# Generated by Django 5.2.3 on 2025-07-04 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='captured_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
